host: '127.0.0.1'
port: 8848
namespace: 'c1872978-d51c-4188-a497-4e0cd20b97d5'
user: 'nacos'
password: 'nacos'
dataid: 'user-web.json'
group: 'dev'

log:
  "level": "debug",
  "filename": "user-web/logs/app.log",
  "max_size": 200,
  "max_age": 7,
  "max_backups": 10